"""
Phase 3 — See the Storm
=======================
You cannot defend what you cannot see. Two deliverables:

  1. A triage report (workspace/reports/noise-report.md) generated by your own
     collect-triage.yml — it must name the storm's CURRENT source IP, which you
     can only know by gathering evidence off the live fleet.
  2. Fleet-wide log forwarding, so the SOC sees the attack from one place.
"""
import os

import pytest

from conftest import TARGETS, run_ansible, _workspace_dir


def _report_path():
    return os.path.join(_workspace_dir(), "reports", "noise-report.md")


class TestPhase3Observability:

    def test_triage_report_exists(self):
        p = _report_path()
        assert os.path.isfile(p) and os.path.getsize(p) > 40, (
            "ARIA: No triage report at workspace/reports/noise-report.md. Write a "
            "collect-triage.yml that gathers the attack evidence from the fleet and "
            "renders a Jinja2 report, then run it."
        )

    def test_triage_report_names_current_ioc(self, noise):
        p = _report_path()
        if not os.path.isfile(p):
            pytest.skip("Triage report not generated yet")
        ioc = noise.active_source_ip()
        if ioc is None:
            pytest.fail(
                "ARIA: The range is not reporting a source IP — INCONCLUSIVE. "
                "Run 'make reset', then 'make test' again."
            )
        with open(p) as f:
            report = f.read()
        assert ioc in report, (
            f"ARIA: Your triage report does not name the storm's current source IP "
            f"({ioc}). Gather the evidence from the live fleet (auth logs) and render "
            f"the top offender into the report — do not hand-write it."
        )

    def test_log_forwarding_configured(self):
        # An uncommented '@host' / '@@host' forward rule must exist on every node.
        r = run_ansible([
            "ansible", "all", "-m", "shell", "-a",
            "grep -REq '^[[:space:]]*[^#]*@[0-9A-Za-z]' "
            "/etc/rsyslog.conf /etc/rsyslog.d/",
        ])
        assert r.returncode == 0, (
            "ARIA: Log forwarding is not configured across the fleet. Point rsyslog "
            "at the SOC collector (e.g. '*.* @@172.30.0.11:514') on every node so the "
            "storm can be watched from one place, then re-test."
        )
